updated the Holmes-Storage documentation
HolmesProcessing/Holmes-Storage pull request #61
Opened 2017-03-31 14:33 UTC by cli0

I added more details and references to the documentation.

2017-03-31 14:54 UTC, webstergd requested changes
looks awesome. Thanks @cli0 

I made some suggestions / quick fixes

2017-03-31 14:54 UTC, webstergd commented on README.md
>  - Local File System
we dropped local file system in version 2 of storage. given mino is so easy to install I don't see a use case for adding it back anytime soon. mind removing this bullet please

2017-03-31 14:54 UTC, webstergd commented on README.md
> +Object Stores are responsible for storing the file-based malicious objects collected by the analyst: binary files such as PE32 and ELF, PDFs, HTML code, Zips files etc. Document Stores are contain th
Document Stores are contain => Document Stores contain 

Document Stores are contain the results of the Holmes-Totem and Holmes-Totem-Dynamic analytic results of the files in Object Stores. => Document Stores contain the output of Holmes-Totem and Holmes-Totem-Dynamic Services.

2017-03-31 14:54 UTC, webstergd commented on README.md
> +- [AWS](https://aws.amazon.com/) for cloud computing, industry and large-scale implementation
might be good to have this as a table. Maybe we could have columns  for workstation, midsized, and large-scale

2017-03-31 14:54 UTC, webstergd commented on README.md
> +Holmes-Storage supports single node or cluster installation of Cassandra version 3.5.x and higher. The version requirement is because of the significant improvement in system performance when leverag
we should bump this up to 3.10. Cassandra did a lot of bug fixes for sasi and material views. 3.5 works...3.10 works a lot better.

leveraging the newly introduced [SASIIndex](https://github.com/apache/cassandra/blob/trunk/doc/SASI.md) for secondary indexing. => leveraging the newly introduced [SASIIndex](https://github.com/apache/cassandra/blob/trunk/doc/SASI.md) and Material Views [need a link]

2017-03-31 15:09 UTC, cynexit commented
Nice job, I agree with Georges changes. We might bring back local-fs later but for now it's definitely gone.

2017-03-31 15:52 UTC, webstergd approved these changes

2017-03-31 15:53 UTC, merged

2017-04-07 08:51 UTC, ms-xy commented
@cynexit regarding local-fs is it incompatible with changes or just nobody that updated it? I do use it all the time for testing :P